Add Dotbot-brew as a plugin

diff --git a/install b/install
--- a/install
+++ b/install
@@ -9,7 +9,24 @@ DOTBOT_BIN="bin/dotbot"
 BASEDIR="$(cd "$(dirname "${(%):-%x}")" && pwd)"
 
 cd "${BASEDIR}"
-git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
-git submodule update --init --recursive "${DOTBOT_DIR}"
+git -C "${BASEDIR}" submodule sync --quiet --recursive
+git submodule update --init --recursive "${BASEDIR}"
 
-"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
+case `uname -m` in
+    arm64)
+        HOMEBREW_DIR="/opt/homebrew";;
+    x86_64)
+        HOMEBREW_DIR="/usr/local";;
+    *)
+        echo "Unknown architecture, can't determine homebrew location!"
+        exit 1;;
+esac
+
+# We need to export variables so that Homebrew and installed programs can be
+# found later on by scripts.
+export HOMEBREW_DIR
+export HOMEBREW_BIN="$HOMEBREW_DIR/bin"
+export PATH="$HOMEBREW_BIN:$PATH"
+
+"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" \
+    --plugin-dir dotbot-brew -c "${CONFIG}" "${@}"
